-- MySQL Script generated by MySQL Workbench
-- Tue Feb 21 18:51:02 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lawyer_tasks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lawyer_tasks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lawyer_tasks` DEFAULT CHARACTER SET utf8 ;
USE `lawyer_tasks` ;

-- -----------------------------------------------------
-- Table `lawyer_tasks`.`States`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lawyer_tasks`.`States` (
  `idState` INT NOT NULL,
  `State` VARCHAR(45) NULL,
  PRIMARY KEY (`idState`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lawyer_tasks`.`Cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lawyer_tasks`.`Cities` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(100) NULL,
  `idState` INT NOT NULL,
  PRIMARY KEY (`idCity`),
  INDEX `fk_Cities_States_idx` (`idState` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_States`
    FOREIGN KEY (`idState`)
    REFERENCES `lawyer_tasks`.`States` (`idState`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lawyer_tasks`.`Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lawyer_tasks`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(100) NULL,
  `number` VARCHAR(10) NULL,
  `neighbourhood` VARCHAR(100) NULL,
  `zipCode` VARCHAR(9) NULL,
  `Cities_idCity` INT NOT NULL,
  PRIMARY KEY (`idAddress`),
  INDEX `fk_Address_Cities1_idx` (`Cities_idCity` ASC) VISIBLE,
  CONSTRAINT `fk_Address_Cities1`
    FOREIGN KEY (`Cities_idCity`)
    REFERENCES `lawyer_tasks`.`Cities` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lawyer_tasks`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lawyer_tasks`.`Customers` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `nationality` VARCHAR(45) NULL,
  `civilStatus` VARCHAR(45) NULL,
  `profession` VARCHAR(100) NULL,
  `identity` VARCHAR(45) NULL,
  `cpf` VARCHAR(11) NULL,
  `phone` VARCHAR(13) NULL,
  `email` VARCHAR(45) NULL,
  `id` VARCHAR(36) NULL,
  `idAddress` INT NOT NULL,
  `registerDate` DATETIME NULL,
  `lastUpdate` DATETIME NULL,
  PRIMARY KEY (`idCustomer`),
  INDEX `fk_Customers_Address1_idx` (`idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_Address1`
    FOREIGN KEY (`idAddress`)
    REFERENCES `lawyer_tasks`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lawyer_tasks`.`Lawyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lawyer_tasks`.`Lawyer` (
  `idLawyer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `nationality` VARCHAR(45) NULL,
  `civilStatus` VARCHAR(45) NULL,
  `profession` VARCHAR(100) NULL,
  `identity` VARCHAR(45) NULL,
  `cpf` VARCHAR(11) NULL,
  `phone` VARCHAR(13) NULL,
  `email` VARCHAR(45) NULL,
  `oabNumber` VARCHAR(45) NULL,
  `id` VARCHAR(36) NOT NULL,
  `Address_idAddress` INT NOT NULL,
  `registerDate` DATETIME NULL,
  `lastUpdate` DATETIME NULL,
  PRIMARY KEY (`idLawyer`),
  INDEX `fk_Lawyer_Address1_idx` (`Address_idAddress` ASC) VISIBLE,
  CONSTRAINT `fk_Lawyer_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `lawyer_tasks`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lawyer_tasks`.`Attorney`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lawyer_tasks`.`Attorney` (
  `idAttorney` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(200) NULL,
  `id` VARCHAR(36) NULL,
  `idCustomer` INT NOT NULL,
  `registerDate` DATETIME NULL,
  PRIMARY KEY (`idAttorney`),
  INDEX `fk_Attorney_Customers1_idx` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `fk_Attorney_Customers1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `lawyer_tasks`.`Customers` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lawyer_tasks`.`Attorney_has_Lawyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lawyer_tasks`.`Attorney_has_Lawyer` (
  `idAttorney` INT NOT NULL,
  `idLawyer` INT NOT NULL,
  PRIMARY KEY (`idAttorney`, `idLawyer`),
  INDEX `fk_Attorney_has_Lawyer_Lawyer1_idx` (`idLawyer` ASC) VISIBLE,
  INDEX `fk_Attorney_has_Lawyer_Attorney1_idx` (`idAttorney` ASC) VISIBLE,
  CONSTRAINT `fk_Attorney_has_Lawyer_Attorney1`
    FOREIGN KEY (`idAttorney`)
    REFERENCES `lawyer_tasks`.`Attorney` (`idAttorney`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attorney_has_Lawyer_Lawyer1`
    FOREIGN KEY (`idLawyer`)
    REFERENCES `lawyer_tasks`.`Lawyer` (`idLawyer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
